Pl 569
BBOXX/slate pull request #10
Opened 2021-02-03 08:52 UTC by barkatkhan-bboxx

1. Updated documentation of Appliance Repair Appliance Part TypeLinker 
2. Updated documentation of Appliance Part Type Replacement Linker

2021-02-03 11:09 UTC, bryntruscott requested changes
Most of these files should not have changed. Only the changes to these 2 files are needed:

source/includes/_appliance_part_type_replacement_linker.md
source/includes/_appliance_repair_appliance_part_type_linker.md

2021-02-03 11:09 UTC, bryntruscott commented on source/includes/_appliance_part_type_replacement_linker.md
> +__max_part_count__  <br><font color="DarkGray">_int_</font> <font color="Crimson">(not-null,default=1)</font>| Count of appliance_part_types for each Appliance
"Maximum number of parts of this type that can be replaced for this appliance type"

2021-02-03 11:09 UTC, bryntruscott commented on source/includes/_appliance_repair_appliance_part_type_linker.md
> +__repaired_parts_count__  <br><font color="DarkGray">_int_</font> | Count of parts inserted for each Appliance Repair
"Number of parts of this type replaced in this repair"

2021-02-04 11:02 UTC, bryntruscott requested changes
Thanks for making those changes but you still need to remove all the other files from this pull request as I commented last time. Only these 2 files should be updated:

source/includes/_appliance_part_type_replacement_linker.md
source/includes/_appliance_repair_appliance_part_type_linker.md

2021-02-09 11:28 UTC, closed without merging

2021-02-09 11:29 UTC, barkatkhan-bboxx commented
It is incorrect