added 'current_enable_status' endpoint details
BBOXX/slate pull request #15
Opened 2021-05-05 16:53 UTC by Wajahat-Bboxx

2021-05-11 09:53 UTC, mujeeb-bboxx requested changes

2021-05-11 09:53 UTC, mujeeb-bboxx commented on source/includes/_current_enable_status.md
> +payload={}
This is a GET request, so there is no need to add `payload`.

2021-05-11 09:53 UTC, mujeeb-bboxx commented on source/includes/_current_enable_status.md
> +}
Use same header as in other files, which is this,
`headers = {'Content-Type': 'application/json', 'Authorization': 'Token token=A_VALID_TOKEN'}`

2021-05-11 09:53 UTC, mujeeb-bboxx commented on source/includes/_current_enable_status.md
> +response = requests.request("GET", url, headers=headers, data=payload)
No need to add `payload` and use `requests.get(url=url, headers=headers)` instead.

2021-05-11 09:53 UTC, mujeeb-bboxx commented on source/index.html.md
> +  - current_enable_status.md
No need to add _.md_

2021-05-17 05:45 UTC, mujeeb-bboxx requested changes

2021-05-17 05:45 UTC, mujeeb-bboxx commented on source/includes/_current_enable_status.md
> +response = requests.request("GET", url, headers=headers)
Use `requests.get(url=url, headers=headers)` instead.

2021-05-17 10:11 UTC, mujeeb-bboxx requested changes

2021-05-17 10:11 UTC, mujeeb-bboxx commented on source/includes/_current_enable_status.md
> +
Please remove these two lines.

2021-05-17 10:45 UTC, barkatkhan-bboxx approved these changes

2021-05-17 10:47 UTC, mujeeb-bboxx approved these changes

2021-05-18 06:47 UTC, merged